#!/bin/sh
# Source: https://dev.to/akdevcraft/git-pre-hook-pre-commit-hook-with-npm-project-44p2

git fetch origin

if [[ $(git diff --name-only origin/main -- ./.github ./public ./src ./package-lock.json ./package.json ./tsconfig.json) ]]; then
  echo "Running linter and tests before commit"

  npm run lint -- --max-warnings=0
  npm test -- --watchAll=false

  status=$?
  exit $status
else 
  echo "Nothing to build in compare with 'main' branch" && exit 1
fi
